// ─── A tool's real logo ──────────────────────────────────────────────────────
//
// The Shelf used to draw two-letter INITIALS — "n8", "OD", "ER" — which is a placeholder, and it
// made a catalogue of real software read as a list of abbreviations.
//
// The marks come from `toolLogos.ts`, which is generated by a script that downloads each one from
// the project's own repository. **None of them is drawn from memory.** That rule exists because the
// Claude mark in Connect Apps was drawn by eye twice and was wrong both times; eighteen of those
// would have been eighteen subtly-wrong logos that nobody catches until a customer does.
//
// Three shapes arrive, because three is what the projects actually publish:
//   - `path` — a single-path Simple Icons mark plus its brand colour. The best case by far.
//   - `svg`  — the project's own multi-shape file, passed through in its own viewBox.
//   - `png`  — a raster, for the projects that publish no usable vector mark.

import { markFor } from '../lib/toolLogos';

/**
 * ── WHY EVERY MARK SITS ON A TILE ───────────────────────────────────────────
 *
 * Eighteen logos from eighteen projects have nothing in common. Put them straight onto the dark
 * rail and it showed: Dolibarr's navy "D" and Zammad's near-black glyph disappeared entirely,
 * Open WebUI arrived as a bright white card, and EspoCRM and Flowise brought their own coloured
 * backgrounds — so the rail read as a jumble of tiles, smudges and gaps rather than a set.
 *
 * A single neutral ground behind all of them fixes every one of those at once, which is why every
 * operating system and app store does it. A dark mark now has something to be dark against, a mark
 * with its own background is framed rather than floating, and the rail reads as one row of software.
 *
 * It also keeps the trademark side clean: the mark is never recoloured to fit our palette. It is put
 * on a neutral card, exactly as published.
 */
const TILE = 'shrink-0 flex items-center justify-center rounded-[5px] bg-white '
  + 'ring-1 ring-black/10 overflow-hidden';

export default function ToolMarkIcon({ id, name, size = 22, className }: {
  id: string;
  /** Only used for the fallback and for the accessible label. */
  name: string;
  /** Outer tile size in px. The mark is inset within it. */
  size?: number;
  className?: string;
}) {
  const mark = markFor(id);
  // The mark is inset so it never runs to the very edge of its card — the same small courtesy an
  // app icon gets, and what stops a square logo looking wedged in.
  const inner = Math.round(size * 0.76);
  const wrap = (child: React.ReactNode) => (
    <span className={`${TILE} ${className ?? ''}`} style={{ width: size, height: size }}>{child}</span>
  );

  // A tool with no mark keeps the old initials rather than a blank square — a missing logo should
  // look like a tool we have not got a logo for, not like a broken one.
  if (!mark) {
    const parts = name.replace(/\./g, ' ').split(/\s+/).filter(Boolean);
    const text = parts.length === 1
      ? parts[0].slice(0, 2).toUpperCase()
      : (parts[0][0] + parts[1][0]).toUpperCase();
    return wrap(<span className="text-[9px] font-bold tracking-tight text-neutral-600">{text}</span>);
  }

  if (mark.kind === 'path') {
    return wrap(
      <svg viewBox="0 0 24 24" width={inner} height={inner} role="img" aria-label={name}>
        {/* The brand's own colour, unaltered. Recolouring someone's mark to match our palette is
            both a worse logo and a worse thing to do with a trademark. */}
        <path d={mark.d} fill={mark.colour} />
      </svg>,
    );
  }

  if (mark.kind === 'svg') {
    return wrap(
      <svg
        viewBox={mark.viewBox}
        width={inner}
        height={inner}
        role="img"
        aria-label={name}
        // The file is generated from a fixed set of project repositories by a script in this repo,
        // never from anything a user or a model supplies — there is no path by which arbitrary
        // markup reaches this.
        dangerouslySetInnerHTML={{ __html: mark.inner }}
      />,
    );
  }

  // A raster that carries its own background fills the tile instead of floating inside it —
  // otherwise the card gets a white border around a coloured square, which reads as a mistake.
  return wrap(<img src={mark.src} alt={name} width={size} height={size} draggable={false} />);
}
